output_directory: data

machine:
  type: serial
  port: /dev/serial/by-id/usb-STMicroelectronics_MARLIN_STM32G0B1RE_CDC_in_FS_Mode_20783671524E-if00
  baud: 115200
  stabilize_delay: 0.15
  speed: 12000
  coordinates:
    x_start: 75
    x_end: 253
    x_inc: 44.5
    y_start: 30
    y_end: 187.5
    y_inc: 22.5
  home:
  - G28 XY  
  - M400
  - M906 X2000 Y2000
  - M203 X15 Y15
camera:
  type: microscope
  id: /dev/v4l/by-id/usb-RaySmartTech_VMS101S_00.00.01-video-index0